### ISSUE TITLE
AZGS toolbar Map Unit Legend Editor yields error messages

### ISSUE THREAD

**Issue by JSpencer1453** [ncgmp09/azgs-toolbar#26]
The Phoenix area geodatabase has been copied to a new geodatabase where I simplified the bedrock units for the benefit of non-geologists who want to use this. Bedrock units were reduced from 190 to 31 units. During the course of simplifying the derivative geodatabase I encountered two reproducible error messages when modifying units in the Map Unit Legend Editor. One message (same key message) is "Unhandled exception has occurred...An item with the same key has already been added" that is triggered after editing Map Unit Legend data for map units d, da, Tsv, Tcg, Qtc, Tb, Tv, Tkg, and YXg. The other is "The given key is not present in the dictionary" and is triggered after editing Map Unit Legend data for map units PPn, Dm, and Qe. I looked in the two tables that have hierarchy keys and all looked good, so I don’t understand why these error messages are appearing. Also, there were not crashes or system brain freezes, so the errors must not be critical. However, this geodatabase is being prepared for release to the public, and it should not have problems if they can be diagnosed and fixed.

**Comment by JSpencer1453** [comment]
Project file is at  P:\STATEMAP13\Phoenix_area\projects
Database is at G:\geologic map data\PhoenixArea_3_simplified_bedrock.gdb

**Comment by jessica-azgs** [comment]
The key these errors are referring to are not the hierarchy keys but keys in dictionary used by the code `m_MapUnitPolysDictionary`. Though the error message seems obvious it doesn't seem to be applicable to what the code is actually doing and is thus not a quick fix. Since this problem is only when using the Toolbar and Map Unit Legend Editor it will not effect the distribution of feature classes from this database for the general public. Also, since this error is not occurring in other databases, after talking to @JSpencer1453, we are tabling this issue for now.
